name: Test and Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
 
jobs:
  build_and_test:
    runs-on: ubuntu-latest
 
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install XVFB for testing with VS Code
        run: |
          sudo apt-get -y update
          sudo apt-get -y install --fix-missing xvfb

      - name: Build
        run: |
          npm ci

      - name: Find VS Code stable release version
        id: code-stable
        run: |
          echo "VSCODE_VERSION=`curl --silent https://update.code.visualstudio.com/api/releases/stable | jq -r '.[0]'`" >> "$GITHUB_OUTPUT"

      - name: Cache VS Code download
        uses: actions/cache@v4
        with:
          path: |
            .vscode-test
          key: vscode-test-cache-${{ steps.code-stable.outputs.VSCODE_VERSION }}

      - name: Test using VS Code
        run: |
          export XDG_RUNTIME_DIR=/run/user/$(id -u)
          export DBUS_SESSION_BUS_ADDRESS=unix:path=$XDG_RUNTIME_DIR/bus
          dbus-daemon --session --address=$DBUS_SESSION_BUS_ADDRESS --nofork --nopidfile --syslog-only &
          mkdir ~/.vscode && echo '{ "disable-hardware-acceleration": true }' > ~/.vscode/argv.json
          xvfb-run -a npm run test